COMPONENT_SUBMODULES := FastLED
COMPONENT_SRCDIRS := $(COMPONENT_SUBMODULES)/src Arch/$(SMING_ARCH)/src/
COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS) 


ifeq ($(SMING_ARCH),Esp32)
	APP_CFLAGS += -DFASTLED_ALL_PINS_HARDWARE_SPI
endif
