COMPONENT_SUBMODULES := FastLED
COMPONENT_SRCDIRS := $(COMPONENT_SUBMODULES)/src

ifeq ($(SMING_ARCH),Esp8266)
	COMPONENT_SRCDIRS += $(COMPONENT_SUBMODULES)/src/platform/esp/8266
	APP_CFLAGS += -DFASTLED_ESP8266_RAW_PIN_ORDER
endif

ifeq ($(SMING_ARCH),Esp32)
	COMPONENT_SRCDIRS += $(COMPONENT_SUBMODULES)/src/platform/esp/32
	APP_CFLAGS += -DFASTLED_ESP32_RAW_PIN_ORDER
endif

COMPONENT_INCDIRS := $(COMPONENT_SRCDIRS) 