COMPONENT_SUBMODULES	+= lvgl

LVGL_ROOT := $(COMPONENT_PATH)/lvgl
COMPONENT_SRCDIRS := $(LVGL_ROOT)/src \
					$(call ListAllSubDirs,$(LVGL_ROOT)/src)
					
COMPONENT_INCDIRS := $(COMPONENT_PATH) $(LVGL_ROOT)